global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pulse-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pulse-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
