apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-app
  namespace: default
  labels:
    app: pulse
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pulse
  template:
    metadata:
      labels:
        app: pulse
        version: v1
    spec:
      serviceAccountName: pulse-app
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: pulse
        image: pulse:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: jwt-secret
        - name: VITE_APP_ID
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: vite-app-id
        - name: OAUTH_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: oauth-server-url
        - name: VITE_OAUTH_PORTAL_URL
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: vite-oauth-portal-url
        - name: OWNER_OPEN_ID
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: owner-open-id
        - name: OWNER_NAME
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: owner-name
        - name: VITE_APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: app-title
        - name: VITE_APP_LOGO
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: app-logo
        - name: BUILT_IN_FORGE_API_URL
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: forge-api-url
        - name: BUILT_IN_FORGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: forge-api-key
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pulse
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: pulse-app
  namespace: default
  labels:
    app: pulse
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: pulse
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pulse-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pulse-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
